repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.3.0
    hooks:
    - id: flake8
      args: [--max-line-length=88]
    - id: end-of-file-fixer
    - id: requirements-txt-fixer
    - id: check-added-large-files
    - id: check-json
    - id: pretty-format-json
      args: [--autofix]
-   repo: https://github.com/psf/black
    rev: "24.2.0"
    hooks:
    -   id: black
        args: [--config=black.toml]
